- label: 'Setup'
  message: 'Completed'
  color: 'green'
- message: 'Work in Progress'
  color: 'yellow'
  when: "$labels.includes('WIP')"
- label: 'Size'
  message: 'Large PR'
  color: 'red'
  when: '$additions > 500 || $deletions > 500'
- label: 'Size'
  message: 'Small PR'
  color: 'green'
  when: '$additions < 200 || $deletions < 200'
- label: 'Preview'
  message: 'Click here!'
  color: 'yellow'
  url: 'https://pr-{{context.issue.number}}.parthibanbaskar.vercel.app'
- message: '$commits commits across $changedFiles files'
  color: 'crimson'
